version: '3'

services:
  api-gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - ${PORT}:8001

